### ISSUE TITLE
Save Issue

### ISSUE THREAD

**Issue by ahaanghosh747** [tcpd/surf#11]
Saving takes a few seconds. 

Saving sometimes causes Surf to crash, thereby forcing the user to redo merges again.
(If possible, freezing of the groups without refreshing the entire video)

Saving also causes the groups to shift around.

**Comment by ahaanghosh747** [comment]
![surf error](https://user-images.githubusercontent.com/30865297/29159514-6e74c6be-7dcc-11e7-9e88-17529f2e235a.PNG)

**Comment by hangal** [comment]
@sudesh-ashoka what does the stack trace point to?

**Comment by hangal** [comment]
not relevant now, closing.
