### ISSUE TITLE
Name should show canonicalized variant on hover

### ISSUE THREAD

**Issue by hangal** [tcpd/surf#13]
Would be useful for debugging.

**Comment by hangal** [comment]
Implemented canonical variants on hover on name
and pc num and sub region on hover on ac_no.

![screen shot 2017-08-09 at 10 29 51 pm](https://user-images.githubusercontent.com/1018175/29133853-6c53e740-7d52-11e7-8f12-8345c65701b3.png)

![screen shot 2017-08-09 at 10 31 23 pm](https://user-images.githubusercontent.com/1018175/29133896-91804f54-7d52-11e7-88b0-e1f9ec12a408.png)

**Comment by Sudesh-Prakash-Singh** [comment]
Test Pass.
Closing.
