### ISSUE TITLE
Pressing the save button after merge goes into infinite loading screen on Windows

### ISSUE THREAD

**Issue by Sudesh-Prakash-Singh** [tcpd/surf#2]
Pressing the save button after merge goes into infinite loading screen on Windows.
The mastersheet isn't updated either.

**Comment by hangal** [comment]
Not relevant any more (?)
@sudesh-ashoka pls confirm

**Comment by Sudesh-Prakash-Singh** [comment]
This was fixed. But not relevant anymore in the new build.
Closing.
