### ISSUE TITLE
Rows dissapear after merging and then refreshing

### ISSUE THREAD

**Issue by Sudesh-Prakash-Singh** [tcpd/surf#20]
Steps:
1) Select rows for Merging
2) Press the Merge button
3) Scroll down to merged records
4) Refresh the page

Expected:
Merged records should be visible

Actual:
Merged records disappear.

![records dissapear s2](https://user-images.githubusercontent.com/19662760/29615264-d84ab4e6-882a-11e7-93fd-72fbcb3ab1cf.png)
![records disappear s1](https://user-images.githubusercontent.com/19662760/29615263-d848ac64-882a-11e7-8573-297beaefc2a7.png)

**Comment by hangal** [comment]
@sudesh can you demo this to me in person?

**Comment by hangal** [comment]
@sudesh-ashoka is this still an issue

**Comment by Sudesh-Prakash-Singh** [comment]
Was the same Issue as sorting of groups. Closing.
