### ISSUE TITLE
Constituency Field is blank on GE data

### ISSUE THREAD

**Issue by Sudesh-Prakash-Singh** [tcpd/surf#21]
Constituency Field doesn't display constituency when working with GE data.

**Comment by hangal** [comment]
What file are you using?
That seems to be because Constituency it is not present in the candidates_electoral_info.csv file.
 Did you join it with the const_electoral_info file?

**Comment by hangal** [comment]
@sudesh-ashoka still an issue?

**Comment by hangal** [comment]
@sudesh-ashoka still an issue?

**Comment by Sudesh-Prakash-Singh** [comment]
Sorry, missed out on this. Yes, this is resolved
