### ISSUE TITLE
Unwanted states showing on applying state filter

### ISSUE THREAD

**Issue by Sudesh-Prakash-Singh** [tcpd/surf#22]
Steps:
1) Select GE data on start page.
2) Select Compatible names algorithm.
3) Apply filter State_name=karnataka
4) Go to page 2 after the dataset loads

Expected:
rows with state filter applied should display.

Actual:
1) Unwanted States are displayed in rows.
2) Page takes time to load.
3) Eventually, the page crashes.

**Comment by hangal** [comment]
New version has an option to show only rows matching the filter exactly.
Please test and see if it serves the purpose.

**Comment by Sudesh-Prakash-Singh** [comment]
Tested.
Page doesn't crash anymore.
Closing.
