### ISSUE TITLE
Clicking on candidate name does not search with the name and constituency

### ISSUE THREAD

**Issue by Sudesh-Prakash-Singh** [tcpd/surf#23]
Clicking on candidate name hyperlink does not search with name and constituency anymore. Google search is only done on the Year.

**Comment by hangal** [comment]
This was a bug because the name of the field is different.
We should simply call the field "Name" instead of "Cand", etc.

**Comment by Sudesh-Prakash-Singh** [comment]
Test Pass.
Closing.
