### ISSUE TITLE
Irrelevant rows showing up in edit distance 1

### ISSUE THREAD

**Issue by Sudesh-Prakash-Singh** [tcpd/surf#26]
Irrelevant rows show up in edit distance 1.

See attached screenshot for details.
![screenshot from 2017-09-04 15-46-42](https://user-images.githubusercontent.com/19662760/30023295-6392290c-918c-11e7-8019-f9fb2c271c38.png)

**Comment by hangal** [comment]
Hmm... interesting. I can reproduce it. The behavior is unexpected, but explainable.
This may be happening because There is a e.d. 1 path from KHUSHI RAM to TELU RAM via people in other states. But you're not seeing them because your filter is set to show only rows matching filter directly.

**Comment by hangal** [comment]
the solution now is to apply the filter before the algorithm is run.

**Comment by hangal** [comment]
not a bug, this is how the algorithm works.

**Comment by Sudesh-Prakash-Singh** [comment]
Closing.
