### ISSUE TITLE
Some Merges suggested by Gilles in Gujarat AE are not being covered in Compatible Names.

### ISSUE THREAD

**Issue by Sudesh-Prakash-Singh** [tcpd/surf#30]
Compatible Names is not covering few of the cases in Gujarat AE.
Attaching the correction File.
[1967 Gujarat corrections.xlsx](https://github.com/tcpd/surf/files/1287904/1967.Gujarat.corrections.xlsx)

Eg:
AC_name	Position	Cand1
BABRA	1	J. D. KANSAGRA
BABRA	3	JINABHAI D KANASAGARA
BABRA	1	KANSAGRA JINA DEVRAJ

BARODA CITY	1	C.K. PARIKH
BARODA CITY	1	CHANDRAKANT M PARIKH

**Comment by Sudesh-Prakash-Singh** [comment]
@hangal 

M.F. SOLANKI is present in the sheet on which I was testing.

**Comment by hangal** [comment]
M.F. SOLANKI was being parsed as MF SOLANKI, not M F SOLANKI.
Now fixed.

**Comment by Sudesh-Prakash-Singh** [comment]
Test Pass. Closing.
