### ISSUE TITLE
Group Order changes on page refresh

### ISSUE THREAD

**Issue by Sudesh-Prakash-Singh** [tcpd/surf#31]
Group order changes after a merge or unmerge is done and page is refreshed.

**Comment by Sudesh-Prakash-Singh** [comment]
@hangal I have recently realized that the sort is happening based on whether merges is happening on group or not. So all the merged groups show up at the beginning. While the unmerged group show at the end.  It seems like there is some kind of sort happening based on number of person in a group. Could this be the cause of the issue?

**Comment by hangal** [comment]
was a bug in sorting the groups by string length. fixed the bug and introduced a more stable way of ordering the groups. Could be slow, please check.

**Comment by Sudesh-Prakash-Singh** [comment]
Test Pass. Group order is stable now.
