### ISSUE TITLE
Reviewed color should stay persistant until the algorithm is switched.

### ISSUE THREAD

**Issue by Sudesh-Prakash-Singh** [tcpd/surf#32]
Reviewed color of the group disappears on page refresh.
It should stay persistent atleast for the session, while the algorithm is not switched.

**Comment by Sudesh-Prakash-Singh** [comment]
@hangal As you have mentioned this as a partial fix, please let me know, whether it's ok to close this issue. Or if we are expecting further enhancement?

**Comment by hangal** [comment]
we can close it.
partial because we can have a much more powerful and general impl. of labels in the future.
e.g. you could label a row as: "mark for secondary review", etc.

**Comment by Sudesh-Prakash-Singh** [comment]
Understood. Closing.
