### ISSUE TITLE
Spurious merges in Compatible name algorithm

### ISSUE THREAD

**Issue by hangal** [tcpd/surf#35]
Names like MOHANLAL LALJI get converted to MOHAN, which then brings in all names that have MOHAN in them.

**Comment by hangal** [comment]
Also, A RATHOD gets mapped to  ANIL MOHAN PATEL RATHOD, which gets mapped to A.M. PATEL, etc. so a lot of PATEL's and RATHOD's get merged, leading to a group size of 1800, even with a requirement of 3 tokens overlapping.

**Comment by hangal** [comment]
This is not a bug per se -- it is how the algorithm works.

**Comment by Sudesh-Prakash-Singh** [comment]
Closing.
