### ISSUE TITLE
Changes in format of worksheets for Surf

### ISSUE THREAD

**Issue by hangal** [tcpd/surf#4]
Only provide candidates table merged with PC name as input to surf.

**Comment by hangal** [comment]
Along with PC name, also carry over district, sub region info and DelimId, sa_no.

Pls write an R script to assemble these together automatically for all states.

@Rajkamalsingh23 what is the way to map sa_no to delim_id for each state? (I assume there is a way).

I suggest you call these e.g. Karnataka.surf.worksheet instead of mastersheet to avoid confusion with any other kind of files.

In the Surf interface, if a row has a valid district or sub region, we can place it in the title attribute of the constituency HTML element so that it is shown upon hover. e.g. the title attribute for the AC name RATABARI should say "District: KARIMGANJ, Sub-region: SOUTHERN ASSAM (BARAK VALLEY)" 

Based on user feedback, we can show this info right next to AC/PC name without needing to hover. But for now, hover is sufficient.

**Comment by Sudesh-Prakash-Singh** [comment]
@hangal @Rajkamalsingh23 
How do I uniquely identify DelimID, District_Name, Sub_Region?
The data I found in constituency_region_info.csv doesn't have a sa_no. And I think AC_no is not enough to uniquely identify these variables.

**Comment by hangal** [comment]
I suggest checking with @Rajkamalsingh23 or @chinuhub

**Comment by chinuhub** [comment]
@sudesh-ashoka constituency_region_info.csv does not contain sa_no because region wise mapping is not election dependent. It is a property of delimitation which in turn is the property of election year or sa_no. The mapping of delimitation number and year is in DelimID.csv file present in the topmost directory structure of tcpd_data.

**Comment by Sudesh-Prakash-Singh** [comment]
I have pushed the script in git repository under scripts directory.
Name of the script: surf_worksheet_generator.R
Please review it.

**Comment by hangal** [comment]
closed
