### ISSUE TITLE
Difference in the separators

### ISSUE THREAD

**Issue by apratim1** [tcpd/surf#41]
![seperator](https://user-images.githubusercontent.com/32013300/30639238-b280a552-9e1b-11e7-9500-b8f863503d6a.png)

Some   of   the   entries   have   “-”   as   the   separator   while   some   had   “.”   as   the   seperator.

**Comment by hangal** [comment]
Ok, but why is this a Surf bug?

**Comment by Sudesh-Prakash-Singh** [comment]
Not a bug. Surf just outputs whatever data is present in worksheet.
