### ISSUE TITLE
Minor Bug

### ISSUE THREAD

**Issue by apratim1** [tcpd/surf#43]
![given name](https://user-images.githubusercontent.com/32013300/30639336-0a52384a-9e1c-11e7-965f-274447dcaefb.png)

The   second   entry   with   maximum   edit   distance=2.   Gave   this   bug   where   the   name included   Given   Name   and   the   abbreviated   name   in   parenthesis.

**Comment by Sudesh-Prakash-Singh** [comment]
Not a bug.
