### ISSUE TITLE
Possibly Same person in different groups

### ISSUE THREAD

**Issue by Sudesh-Prakash-Singh** [tcpd/surf#44]
Same person exists in different group on different pages. These cannot be merged using surf right now.

Check screenshot for details.

![name clustering issue-2](https://user-images.githubusercontent.com/19662760/31328097-cc7bedf2-acf0-11e7-9902-1798db4bb1a8.png)
![name clustering issue](https://user-images.githubusercontent.com/19662760/31328098-cc8b3a5a-acf0-11e7-8fec-69dab4225b63.png)

**Comment by hangal** [comment]
please filter by regex in the opening screen, it will only list the groups with that string (and probably on the same page.) Then you can merge

**Comment by Sudesh-Prakash-Singh** [comment]
Will be using workaround for now.
