### ISSUE TITLE
De-selecting Select All

### ISSUE THREAD

**Issue by JibraanMansoor** [tcpd/surf#9]
If we have to deselect a row that we selected together, we have to de-select them individually, and then figure out the merges, could it be possible to have a deselect all button so that all rows are deselected within the same group?

**Comment by hangal** [comment]
@sudesh-ashoka this seems to be a valid request. pls implement asap.

**Comment by hangal** [comment]
now implemented.

**Comment by Sudesh-Prakash-Singh** [comment]
Test pass.
Closing.
